spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-route
              uri: http://localhost:28081
              predicates:
                - Path=/api/auth/**
            - id: auth-openapi-route
              uri: http://localhost:28081
              predicates:
                - Path=/openapi/auth
              filters:
                - SetPath=/v3/api-docs
