-- Seed the default administrator account from the local admin profile.
-- Login email: admin@edupivot.xyz

INSERT INTO auth_users (id,
                        email,
                        email_verified,
                        display_name,
                        avatar_url,
                        locale,
                        status,
                        created_at,
                        updated_at,
                        last_login_at,
                        created_provider,
                        created_ip,
                        last_login_provider,
                        last_login_ip,
                        login_count,
                        password_hash,
                        role,
                        phone,
                        bio,
                        gender,
                        birthday,
                        theme,
                        notification_enabled,
                        avatar_file_id)
VALUES ('65c551fa-6f5e-45a1-8b08-8faf116d1901',
        'admin@edupivot.xyz',
        TRUE,
        'DaYZ',
        'https://avatars.githubusercontent.com/u/190088992?v=4',
        NULL,
        'ACTIVE',
        TIMESTAMPTZ '2026-06-09 20:07:33.07228+08',
        TIMESTAMPTZ '2026-06-13 00:14:49.439754+08',
        TIMESTAMPTZ '2026-06-13 00:14:49.439754+08',
        'LOCAL',
        NULL,
        NULL,
        NULL,
        0,
        '$2a$10$OD.UnXvZxFVabRAWFB15le6ZCSzAPGe3.DNytrEkkIv0eFGpGmJx2',
        0,
        '18039801656',
        NULL,
        0,
        DATE '2005-03-16',
        'light',
        TRUE,
        NULL) ON CONFLICT (id) DO
UPDATE SET
    email = EXCLUDED.email,
    email_verified = EXCLUDED.email_verified,
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    locale = EXCLUDED.locale,
    status = EXCLUDED.status,
    updated_at = EXCLUDED.updated_at,
    last_login_at = EXCLUDED.last_login_at,
    created_provider = EXCLUDED.created_provider,
    created_ip = EXCLUDED.created_ip,
    last_login_provider = EXCLUDED.last_login_provider,
    last_login_ip = EXCLUDED.last_login_ip,
    login_count = EXCLUDED.login_count,
    password_hash = EXCLUDED.password_hash,
    role = EXCLUDED.role,
    phone = EXCLUDED.phone,
    bio = EXCLUDED.bio,
    gender = EXCLUDED.gender,
    birthday = EXCLUDED.birthday,
    theme = EXCLUDED.theme,
    notification_enabled = EXCLUDED.notification_enabled,
    avatar_file_id = EXCLUDED.avatar_file_id;
