server:
  port: 28081

spring:
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db,redis,diskSpace
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}

springdoc:
  api-docs:
    enabled: true
  packages-to-scan: com.dayz.sc
  paths-to-match: /api/**
  writer-with-order-by-keys: true

scalar:
  enabled: true

edupivot:
  security:
    jwt:
      issuer: sc-edupivot
      ttl: 7d
