<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.dayz</groupId>
        <artifactId>aeroverse-navigator</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>aeroverse-common</artifactId>
    <packaging>pom</packaging>

    <name>AN-Common</name>
    <description>灵境航途后端公共能力模块聚合工程</description>

    <modules>
        <module>aeroverse-common-core</module>
        <module>aeroverse-common-web</module>
        <module>aeroverse-common-security</module>
        <module>aeroverse-common-feign</module>
        <module>aeroverse-common-redis</module>
    </modules>
</project>
