aeroverse:
  security:
    jwt:
      secret: ${AEROVERSE_JWT_SECRET}
  google:
    oauth2:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: ${GOOGLE_REDIRECT_URI}
  github:
    oauth2:
      client-id: ${GITHUB_CLIENT_ID:}
      client-secret: ${GITHUB_CLIENT_SECRET:}
      redirect-uri: ${GITHUB_REDIRECT_URI:}
