spring:
  application:
    name: sc-ai
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
  config:
    import:
      - optional:nacos:sc-edupivot-ai-common.yaml?group=EDUPIVOT_NAVIGATOR&refreshEnabled=true

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - optional:nacos:sc-edupivot-ai-infra-local.yaml?group=EDUPIVOT_LOCAL&refreshEnabled=false

---
spring:
  config:
    activate:
      on-profile: docker
    import:
      - optional:nacos:sc-edupivot-ai-infra-docker.yaml?group=EDUPIVOT_DOCKER&refreshEnabled=false
